// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table account {
  id integer [pk, increment]
  login string [not null, unique]
  password string [not null, note: 'hashed']
  creation_date datetime

  Note: 'Stores user login data'
}

Table user {
  id integer [pk, ref: > account.id]
  f_name string [note: 'first name']
  l_name string [note: 'last name']
  email string
  description string

  Note: 'Stores user personal info'
}

Table project {
  id integer [pk, increment]
  name string [not null]
  manager integer [not null, ref: > user.id, note: 'user that created the project']
  description string
  creation_date datetime
  version string
  deadline datetime

  Note: 'Stores basic project data'
}

Table team {
  id integer [pk, increment]
  name string [not null]
  project integer [not null, ref: > project.id]

  Note: 'Stores team data'
}

Table team_composition {
  team integer [pk, ref: > team.id]
  user integer [pk, ref: > user.id]
  role string

  Note: 'Stores team members'
}

Table task {
  id integer [pk, increment]
  project integer [ref: > project.id]
  name string [not null]
  description string
  creation_date datetime
  deadline datetime
  status integer [not null, note: 'look kanban_status']
  priority integer [note: 'look task_priority']

  Note: 'Stores task info'
}

Table task_team_assignment {
  task integer [pk, ref: > task.id]
  team integer [pk, ref: > team.id]

  Note: 'Links a task to a team'
}

Table task_user_assignment {
  task integer [pk, ref: > task.id]
  user integer [pk, ref: > user.id]

  Note: 'Links a task to a user'
}

Table task_status_history {
  id integer [pk, increment]
  task integer [ref: > task.id]
  old_status integer [not null, note: 'look kanban_status']
  new_status integer [not null, note: 'look kanban_status']
  changed_at datetime

  Note: 'Tracks when a task changed status'
}
